version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: amitgoswami1027/capstone_reverseproxy
  backend_user:
    build:
      context: ../../restapi-user
    image: amitgoswami1027/capstone_restapi-user
  backend_feed:
    build:
      context: ../../restapi-feed  
    image: amitgoswami1027/capstone_restapi-feed
  backend_filter:
    build:
      context: ../../restapi-image
    image: amitgoswami1027/capstone_restapi-image
  frontend:
    build:
      context: ../../frontend
      args:
        - BUILD_ENV=production
    image: amitgoswami1027/capstone_frontend
