version: "3"
services:
  reverseproxy:
      image: amitgoswami1027/capstone-reverseproxyv2
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed     
  backend-user:
      image: amitgoswami1027/capstone-restapi-userv2
      volumes:
        - $HOME/.aws:/root/.aws
      env_file: 
        - .env  
  backend-feed:
      image: amitgoswami1027/capstone-restapi-feedv2
      volumes:
        - $HOME/.aws:/root/.aws
      env_file:
        - .env
  backend-image-filter:
      image: amitgoswami1027/capstone-restapi-imagev2
      env_file:
        - .env
  frontend:
      image: amitgoswami1027/capstone-frontend
      ports:
        - "8100:80"
