apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  credentials: TUlJRXBRSUJBQUtDQVFFQXljd3MvbXlQb2thREFBeXN3RUZTWFFqWGNsVDZZd2llQVhvRUFkaEpZ
  a1p4ZUw2UmtmMldHNnc3eC93ZgpXWFRoOGZLc05aMCtyVXNWZUpJS2RaTlRBQVl0RXR3aHpsQXE1
  QzIzd1hTN0JnbUlLQkJTRGNObEFNelBPU01BNzhkOEhKZDd6cUI3Cnl6N3BYbnBsbldnUVJWdFo3
  YUhTWStXMVNmTHo5THB1cU83QUtQUW83aEViV1lwNlcyMWYvbU5aa1VweGdvU2pJRHlBQTIyVXc0
  WmgKOHdDRFJhRjYvQjV4WHZpNFh1VVVMUHNmRmNMM2t0R21KMjMvRURPUUpzOENCTmZzNXdsMkNM
  MHZzbSszUG1sTVBNNU5LcDZ5ZU8wcgpYckhNTmZ4UlhOaHMvSmVMdDNmNm9JaFo0NEZtZU5EL3pH
  MFg0cHpHMXdwa29lM0dETnJGeHdJREFRQUJBb0lCQUR1MFd3T1RueE9HCkJUQTRqOHY2QjZKYkFW
  TmtiUWhyL2tPMWxBWHZ0aGFMZlBzYWR2dFlxZGJhS0gzTXpJR3RJVVJ5WmgwZXZ2S0txbm1YeTl4
  cGtEOEwKbEw1bHZ1TEp1VWIxZDg2VytOYWFiMXhiSjh2R3FkV0l3eTdHZW5wMjdQT1FwaUxHUEpv
  dnJPQTFHbWR0NkpKOHFxaXlIZ3RNWlV6Ugp3dmYvU01wV0Fkeitxc3Bic1U5RnByWWFzNDdsMkxm
  Mm91dHRPMlhJMTFKTFRkcTBHa2JDYXBWSy92dGVMTW02QndOZHhMMUh6MU1qCjN1NzdSeCtWNU1r
  QU9jUDRWbkhxbWhINnc0WXRsWForSElYdFRQbWFXQldaV0pVS0ZGWkQ4bGVkN1NoKzFrc3pPMlhB
  MW1obEJudU4KcURhRitFMVJObXdQVnd3aUcxUDQ3SmlUNzVFQ2dZRUEvWG5sVVdnMlJGd29aMlpG
  UVAvSEkrRDJnbHQ0QUZNWDJmT1E5SXFxS2N3dAowRGFvNG4zdEo2TkpndlU3R2g5czJBVVBYdldM
  ekZPeVBzS3NpMTdkckw3b3FWdXg0ZURzMjVSVzJSQUw0NCt1OWdpYWxrSjJVbzE1CnZ0M3p3SkpZ
  VHh3eVMyU2FzSDZ0RFd4YTJQT3hubmVBYVNlamphRCs3M29EekV6bVJUMENnWUVBeTg2TmRWeFFG
  WUZENUpmU1R0OXUKN2ZsdEtvTE9WYlh1QUZweTN0UkJvU0RFWHJrOUNPVlJEVGFkOU1mSjdRVnhL
  Ny9pcGtmMFQwc0x1bWNURUFieHpZdlhtdFV2MkYvaQpWMzhXOUF0VHlSSC8rWlJWRjlNS0VLajVN
  d2UwYllqSERyZ285YjN2WUFoTndSM2ZTYTZuNHBHcHpSc3I0WGtaWVdDVG1KeHV6MU1DCmdZRUE5
  RVppdnQ5RlhQL0xXRXB3OTBFSDh3Vzd5c2pIanRpRkpkL2FsRENGNko0Q2tLUDhnYm1Gc1N0bGpy
  VXliZXhYQXA5dHZyKzQKS0FPSXhYN3F0YTJJeUE5N1BLdEhkRDFGUmg5Z3l2THg0aTM0R05jVjB6
  VGR2cFRrL1JIODlGcVVqRGpLSjJvZXdYUnk1WHJFMmt1UApvdjNiWEh0ODNPS0lqTlR6a0JHVDRL
  a0NnWUVBa3BydmlQZXhwL2FIaHgxckxFOXZkWUlSOUIyS0hYKzBSODdJaU4vNG9kWjNTNGhHCmpt
  cWV4amwrb0lGREVOdjBUN3RGWjhXa3laRTdTNGd2M3p5UG5nTTFRZXlPOFQvd0NtNmliVVRrcldQ
  a1ZYMU5STWtMbVhaalpFRHIKbWt0a25ZTDkrOS80SElWOG9TbEM0TGJoajRxbXNhTVZDcWxaQjRJ
  NFNmUmxoWDhDZ1lFQWd6N3dUemZzaE5JWlo4QVExWFBNaXd2bgpib2tzWmhiNmNBZklzcXNsbkF2
  SWZTTjFrby9KbTdGV2huWXBSdm43VFQxQldTaTd0Nmp0VjMxb21icWFmK01rd0lJTmVSZ3JDby9C
  CjYyUzlnSE94NDVlemJUT0NqL3JoaVFWYnFiZHNMbndic0hFS3hINGttYmxoYk5YZUw5MFlFeFFq
  dSt4WmluelRKbThzWGE0PQ==

